# Generated by Django 4.1.1 on 2022-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("email", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=32)),
                ("type", models.CharField(default="customer", max_length=32)),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
            ],
        ),
    ]
