<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-15 20:00
=======
# Generated by Django 4.1.1 on 2022-10-15 19:43
>>>>>>> wenqi

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('pages', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
=======
        ("pages", "0002_department"),
    ]

    operations = [
        migrations.DeleteModel(name="Department",),
        migrations.DeleteModel(name="Users",),
>>>>>>> wenqi
    ]
