# Generated by Django 4.1.2 on 2022-10-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
