# Generated by Django 4.1.1 on 2022-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0002_alter_customers_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="operators", name="chargedVehicles",),
        migrations.RemoveField(model_name="operators", name="repairedVehicles",),
        migrations.AlterField(
            model_name="vehicles",
            name="batteryPercentage",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="vehicles", name="latitude", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicles", name="longitude", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="plateNum",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="totalRentalHours",
            field=models.FloatField(default=0),
        ),
    ]
