# Generated by Django 4.1.1 on 2022-11-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0011_alter_payments_paytime"),
        ("e_portal", "0013_rename_manangers_managers_alter_vehicles_cover_and_more"),
    ]

    operations = []
