# Generated by Django 4.1.1 on 2022-10-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers", name="balance", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="customers",
            name="totalSpending",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationshistory",
            name="oid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.operators"
            ),
        ),
        migrations.AlterField(
            model_name="operationshistory",
            name="vid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.vehicles"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="cid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.customers"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="vid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.vehicles"
            ),
        ),
        migrations.AlterField(
            model_name="repairhistory",
            name="oid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.operators"
            ),
        ),
        migrations.AlterField(
            model_name="repairhistory",
            name="vid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.vehicles"
            ),
        ),
        migrations.AlterField(
            model_name="topuphistory",
            name="cid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.customers"
            ),
        ),
    ]
