# Generated by Django 4.1.2 on 2022-10-17 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_portal', '0004_rename_nickname_customers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manangers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
