# Generated by Django 4.1.1 on 2022-10-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0005_manangers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("status", models.CharField(default="unpaid", max_length=16)),
                (
                    "startTime",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                ("endTime", models.DateTimeField(default="")),
            ],
        ),
        migrations.RemoveField(model_name="customers", name="balance",),
        migrations.AddField(
            model_name="customers",
            name="eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vehicles", name="price", field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(name="TopUpHistory",),
        migrations.AddField(
            model_name="order",
            name="cid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.customers"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_portal.vehicles"
            ),
        ),
    ]
