# Generated by Django 4.1.2 on 2022-10-29 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_portal', '0006_order_remove_customers_balance_customers_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationshistory',
            name='oid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operationshistory',
            name='vid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='endTime',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='vid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='vid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repairhistory',
            name='oid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repairhistory',
            name='vid',
            field=models.IntegerField(default=0),
        ),
    ]
