# Generated by Django 4.1.2 on 2022-10-29 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_portal', '0007_alter_operationshistory_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
