# Generated by Django 4.1.1 on 2022-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0009_vehicles_description_vehicles_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="endTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
