# Generated by Django 4.1.1 on 2022-10-31 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0010_alter_order_endtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
