# Generated by Django 4.1.1 on 2022-10-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0010_alter_order_endtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="plateNum",
            field=models.CharField(max_length=7),
        ),
    ]
