# Generated by Django 4.1.1 on 2022-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0011_alter_vehicles_platenum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="locName",
            field=models.CharField(max_length=128),
        ),
    ]
