# Generated by Django 4.1.1 on 2022-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0015_customers_avatar_operators_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="managers",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="resources/img/avatars"),
        ),
    ]
