# Generated by Django 4.1.1 on 2022-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0016_managers_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="avatar",
            field=models.ImageField(
                default="resources/img/avatars/new_user.jpg",
                upload_to="resources/img/avatars",
            ),
        ),
    ]
