# Generated by Django 4.1.1 on 2022-11-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_portal", "0017_alter_customers_avatar"),
    ]

    operations = [
        migrations.RemoveField(model_name="customers", name="address",),
        migrations.RemoveField(model_name="customers", name="updateDate",),
        migrations.RemoveField(model_name="managers", name="updateDate",),
        migrations.RemoveField(model_name="operators", name="updateDate",),
    ]
